#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const IGNORED_DEFAULT = [
    '.git', 'node_modules', 'dist', 'build', 'out', 'package-lock.json', 
    'yarn.lock', '.exe', '.png', '.jpg', '.jpeg', '.gif', '.svg', '.ico', 
    '.pdf', '.zip', '.tar', '.gz', '.db', '.sqlite', 'context_output.md', 'mcf.exe'
];

const BANNER = `
\x1b[38;5;39m    __  ______   ___  __ ______   _________  _  _____________  ________
\x1b[38;5;45m   /  |/  / _ | / _ \\/ //_/ __ \\  / ___/ __ \\/ |/ /_  __/ __/ |/_/_  __/
\x1b[38;5;48m  / /|_/ / __ |/ , _/ ,< / /_/ / / /__/ /_/ /    / / / / _/_>  <  / /   
\x1b[38;5;82m /_/  /_/_/ |_/_/|_/_/|_|\\____/  \\___/\\____/_/|_/ /_/ /___/_/|_| /_/    \x1b[0m

\x1b[1m\x1b[32m >>> MARKO CONTEXT \x1b[0m \x1b[90m| v1.0.0 (Stable)\x1b[0m
\x1b[90m ---------------------------------------------------------------------- \x1b[0m
`;

function generateTree(dir, prefix = '', ignoredList) {
    let tree = '';
    const files = fs.readdirSync(dir);
    const filtered = files.filter(file => !ignoredList.includes(file));

    filtered.forEach((file, index) => {
        const isLast = index === filtered.length - 1;
        const fullPath = path.join(dir, file);
        let stats;
        try { stats = fs.statSync(fullPath); } catch(e) { return; }

        tree += `${prefix}${isLast ? '└── ' : '├── '}${file}\n`;
        if (stats.isDirectory()) {
            tree += generateTree(fullPath, `${prefix}${isLast ? '    ' : '│   '}`, ignoredList);
        }
    });
    return tree;
}

function aggregateContent(dir, currentDir, ignoredList) {
    let content = '';
    const files = fs.readdirSync(currentDir);

    files.forEach(file => {
        const fullPath = path.join(currentDir, file);
        const relativePath = path.relative(dir, fullPath);
        if (ignoredList.some(ig => relativePath.includes(ig))) return;

        let stats;
        try { stats = fs.statSync(fullPath); } catch(e) { return; }

        if (stats.isDirectory()) {
            content += aggregateContent(dir, fullPath, ignoredList);
        } else {
            try {
                const fileData = fs.readFileSync(fullPath, 'utf8');
                content += `\n--- FILE: ${relativePath} ---\n`;
                content += `\`\`\`\n${fileData}\n\`\`\`\n`;
            } catch (e) {}
        }
    });
    return content;
}

async function run() {
    console.log(BANNER);
    const args = process.argv.slice(2);
    const targetDir = args[0] ? path.resolve(process.cwd(), args[0]) : process.cwd();

    if (!fs.existsSync(targetDir)) {
        console.error(`\x1b[31m✘ ERROR:\x1b[0m Path not found: ${targetDir}`);
        return;
    }

    try {
        let output = `# Project Structure\n\n\`\`\`text\n`;
        output += generateTree(targetDir, '', IGNORED_DEFAULT);
        output += `\`\`\`\n\n# Source Code\n`;
        output += aggregateContent(targetDir, targetDir, IGNORED_DEFAULT);
        output += `\n\n---\nGenerated by Marko Context `;

        const outputPath = path.join(targetDir, 'context_output.md');
        fs.writeFileSync(outputPath, output);
        
        try {
            // Windows PowerShell ile panoya kopyalama
            execSync(`powershell -command "Set-Clipboard -Value (Get-Content -Raw '${outputPath}')"`);
        } catch (e) {}

        console.log(`\x1b[32m✔ SUCCESS:\x1b[0m Processed: ${targetDir}`);
        console.log(`\x1b[32m✔ SAVED:\x1b[0m context_output.md created.`);
        console.log(`\x1b[32m✔ CLIPBOARD:\x1b[0m Ready to paste!`);
    } catch (err) {
        console.error(`\x1b[31m✘ ERROR:\x1b[0m`, err.message);
    }
}

run();